#!/bin/sh

if [ ! -h "/opt/brcm" ];then
cd /opt/asus/tools
sudo ln -s ~/opt/asus/tools/brcm /opt/brcm
fi
if [ ! -h "/opt/buildroot-gcc463" ];then
cd /opt/asus/tools
sudo ln -s ~/opt/asus/tools/buildroot-gcc463 /opt/buildroot-gcc463
fi
cd /opt/asus/release/src-ra-5010
export PATH=/opt/brcm/hndtools-mipsel-linux/bin:$PATH
export PATH=/opt/brcm/hndtools-mipsel-uclibc/bin:$PATH
export PATH=/opt/buildroot-gcc463/bin:$PATH
make RT-AC85P
