#!/bin/sh

if [ ! -d "buildroot-gcc463" ];then
echo "=================EXTRACT-buildroot-gcc463================="
cd /opt/asus/tools
sudo tar -jxvf buildroot-gcc463_32bits.tar.bz2
fi
if [ ! -h "/opt/brcm" ];then
sudo ln -s /opt/asus/tools/brcm /opt/brcm
fi
if [ ! -h "/opt/buildroot-gcc463" ];then
sudo ln -s /opt/asus/tools/buildroot-gcc463/usr /opt/buildroot-gcc463
fi
cd /opt/asus/release/src-ra-5010
export PATH=/opt/brcm/hndtools-mipsel-linux/bin:$PATH
export PATH=/opt/brcm/hndtools-mipsel-uclibc/bin:$PATH
export PATH=/opt/buildroot-gcc463/bin:$PATH
make RT-AC85P
